### ISSUE TITLE
pixel.thesemetrics.org flagged as malware

### ISSUE THREAD

**Issue by lorand-horvath** [znckco/thesemetrics#10]
One of your subdomains https://pixel.thesemetrics.org which is seemingly accessed by https://unpkg.com/thesemetrics@latest is being flagged as malware by at least 5 antivirus software, please see virustotal report below:
https://www.virustotal.com/gui/url/8110f0a1c991a53e5bee13d804f2bcf972d7da2f6b0fc9fd44160d8b912d1480

In my case, Avast reports this website as infected https://pinia.vuejs.org

**Comment by znck** [comment]
AVG team confirmed that they have fixed it. If you're still seeing it, can you provide screenshot of the error?

**Comment by znck** [comment]
Thanks for sharing the virustotal link. I'll write to all the security vendors and setup monitoring.

**Comment by lorand-horvath** [comment]
> AVG team confirmed that they have fixed it. If you're still seeing it, can you provide screenshot of the error?

@znck I've just checked and Avast 23.2 is not reporting it as malware anymore. As you probably know, Avast purchased AVG in 2016, so AVG is basically the same software as Avast for some time now, just a different branding.
Thanks!
